//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Employees
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string JobId { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Salary { get; set; }
        public string Salaries { get; set; }
        public string WorkTime { get; set; }
        public string VacationTime { get; set; }
        public string IdNum { get; set; }
        public string PassportNum { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public Nullable<System.DateTime> DateEndId { get; set; }
        public Nullable<System.DateTime> DateEndPassport { get; set; }
        public string Details { get; set; }
        public string ContractStatus { get; set; }
        public string Gender { get; set; }
        public string WorkTimeInWeak { get; set; }
        public string Rank { get; set; }
        public Nullable<int> AddCount { get; set; }
    }
}
