//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Mandate
    {
        public int Id { get; set; }
        public string ManedateAdmin { get; set; }
        public string MandatesEmp { get; set; }
        public string AboutMandate { get; set; }
        public string MandareDestination { get; set; }
        public string MandateTime { get; set; }
        public Nullable<System.DateTime> MandateDate { get; set; }
        public string MandateReward { get; set; }
        public string MandateResult { get; set; }
        public string Details { get; set; }
    }
}
