//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Projects
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string AdminName { get; set; }
        public string ProjectStatus { get; set; }
        public string Requireds { get; set; }
        public string Cost { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Details { get; set; }
    }
}
