//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Salaries
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string MainSalary { get; set; }
        public string ContractStatus { get; set; }
        public string Salaries { get; set; }
        public Nullable<System.DateTime> CashingDate { get; set; }
    }
}
