//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vacations
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string AboutVacation { get; set; }
        public string VacationAmount { get; set; }
        public Nullable<System.DateTime> VacationStartDate { get; set; }
        public Nullable<System.DateTime> VacationEndDate { get; set; }
    }
}
